/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caro;

/**
 *
 * @author haohao
 */
public class SetName extends javax.swing.JFrame {

    /**
     * Creates new form SetName
     */
    public SetName(Start start) {
        initComponents();
        this.start= start.getModelStart();
        this.settings=start.getSettings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namePlayer1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        namePlayer2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        continute = new javax.swing.JButton();

        setLocation(new java.awt.Point(700, 300));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        namePlayer1.setBackground(new java.awt.Color(240, 240, 240));
        namePlayer1.setFont(new java.awt.Font("UVN Bach Dang Nang", 0, 18)); // NOI18N
        namePlayer1.setForeground(new java.awt.Color(59, 58, 48));
        namePlayer1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(178, 194, 191)));

        jLabel1.setFont(new java.awt.Font("UVN Bach Dang Nang", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(59, 58, 48));
        jLabel1.setLabelFor(namePlayer2);
        jLabel1.setText("Người chơi 2");

        namePlayer2.setBackground(new java.awt.Color(240, 240, 240));
        namePlayer2.setFont(new java.awt.Font("UVN Bach Dang Nang", 0, 18)); // NOI18N
        namePlayer2.setForeground(new java.awt.Color(59, 58, 48));
        namePlayer2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(178, 194, 191)));

        jLabel2.setFont(new java.awt.Font("UVN Bach Dang Nang", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(59, 58, 48));
        jLabel2.setLabelFor(namePlayer1);
        jLabel2.setText("Người chơi 1");

        back.setBackground(new java.awt.Color(189, 87, 52));
        back.setFont(new java.awt.Font("UVN Bach Dang Nang", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Quay lại");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        continute.setBackground(new java.awt.Color(69, 65, 64));
        continute.setFont(new java.awt.Font("UVN Bach Dang Nang", 0, 18)); // NOI18N
        continute.setForeground(new java.awt.Color(255, 255, 255));
        continute.setText("Bắt đầu chơi");
        continute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namePlayer1)
                    .addComponent(namePlayer2))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(continute)
                .addGap(27, 27, 27)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continute)
                    .addComponent(back))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void continuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuteActionPerformed
        this.dispose();
        String name1= "player1";
        String name2 = "player2";
        if(!namePlayer1.getText().equals("")){
            name1 = namePlayer1.getText();
        }
        if(!namePlayer2.getText().equals("")){
            name2 = namePlayer2.getText();
        }    
        new Play(name1,name2,settings.getSizeBoard(),settings.getWidthBoard(),0,0,settings.getTimeLimit(),false,start).setVisible(true);
    }//GEN-LAST:event_continuteActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
    }
    private Settings settings= new Settings();
    private static Start start = new Start();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton continute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namePlayer1;
    private javax.swing.JTextField namePlayer2;
    // End of variables declaration//GEN-END:variables
}
