/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caro;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author haohao
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form mode
     */
    public Settings() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mode = new javax.swing.ButtonGroup();
        limitedTIme = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        board_10 = new javax.swing.JRadioButton();
        board_15 = new javax.swing.JRadioButton();
        board_19 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectedYes = new javax.swing.JRadioButton();
        selectedNo = new javax.swing.JRadioButton();
        TF_TimeLimit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setLocation(new java.awt.Point(700, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        board_10.setBackground(new java.awt.Color(255, 255, 255));
        mode.add(board_10);
        board_10.setFont(new java.awt.Font("UVN Bach Dang Nang", 1, 18)); // NOI18N
        board_10.setForeground(new java.awt.Color(59, 58, 48));
        board_10.setText("10x10");
        board_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                board_10ActionPerformed(evt);
            }
        });

        board_15.setBackground(new java.awt.Color(255, 255, 255));
        mode.add(board_15);
        board_15.setFont(new java.awt.Font("UVN Bach Dang Nang", 1, 18)); // NOI18N
        board_15.setForeground(new java.awt.Color(59, 58, 48));
        board_15.setText("15x15");
        board_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                board_15ActionPerformed(evt);
            }
        });

        board_19.setBackground(new java.awt.Color(255, 255, 255));
        mode.add(board_19);
        board_19.setFont(new java.awt.Font("UVN Bach Dang Nang", 1, 18)); // NOI18N
        board_19.setForeground(new java.awt.Color(59, 58, 48));
        board_19.setSelected(true);
        board_19.setText("19x19");
        board_19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                board_19ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("UVN Bach Dang Nang", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(59, 58, 48));
        jLabel2.setText("Mode:");

        jLabel3.setFont(new java.awt.Font("UVN Bach Dang Nang", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(59, 58, 48));
        jLabel3.setText("Giới hạn thời gian");

        selectedYes.setBackground(new java.awt.Color(255, 255, 255));
        limitedTIme.add(selectedYes);
        selectedYes.setFont(new java.awt.Font("UVN Bach Dang Nang", 1, 18)); // NOI18N
        selectedYes.setForeground(new java.awt.Color(59, 58, 48));
        selectedYes.setSelected(true);
        selectedYes.setText("Yes");
        selectedYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedYesActionPerformed(evt);
            }
        });

        selectedNo.setBackground(new java.awt.Color(255, 255, 255));
        limitedTIme.add(selectedNo);
        selectedNo.setFont(new java.awt.Font("UVN Bach Dang Nang", 1, 18)); // NOI18N
        selectedNo.setForeground(new java.awt.Color(59, 58, 48));
        selectedNo.setText("No");
        selectedNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedNoActionPerformed(evt);
            }
        });

        TF_TimeLimit.setFont(new java.awt.Font("UVN Bach Dang Nang", 1, 18)); // NOI18N
        TF_TimeLimit.setForeground(new java.awt.Color(59, 58, 48));
        TF_TimeLimit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TF_TimeLimit.setText("20");
        TF_TimeLimit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TF_TimeLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_TimeLimitActionPerformed(evt);
            }
        });
        TF_TimeLimit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TF_TimeLimitKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(59, 58, 48));
        jLabel1.setText("s");

        Save.setBackground(new java.awt.Color(59, 58, 48));
        Save.setFont(new java.awt.Font("UVN Bach Dang Nang", 1, 18)); // NOI18N
        Save.setForeground(new java.awt.Color(240, 240, 240));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(189, 87, 52));
        Exit.setFont(new java.awt.Font("UVN Bach Dang Nang", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(240, 240, 240));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selectedYes)
                                .addGap(18, 18, 18)
                                .addComponent(selectedNo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 39, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(board_10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(board_15)))
                        .addGap(40, 40, 40)
                        .addComponent(board_19)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TF_TimeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(board_15)
                        .addComponent(board_19)
                        .addComponent(board_10)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedYes)
                    .addComponent(selectedNo)
                    .addComponent(TF_TimeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit)
                    .addComponent(Save))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void board_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_board_10ActionPerformed
        widthBoard=50;
        sizeBoard=10;
        Save.setBackground(new java.awt.Color(59,58,48));
        Save.setForeground(Color.white);     
    }//GEN-LAST:event_board_10ActionPerformed

    private void board_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_board_15ActionPerformed
        widthBoard=35;
        sizeBoard=15;
        Save.setBackground(new java.awt.Color(59,58,48));
        Save.setForeground(Color.white);
    }//GEN-LAST:event_board_15ActionPerformed

    private void board_19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_board_19ActionPerformed
        widthBoard=28;
        sizeBoard=19;
        Save.setBackground(new java.awt.Color(59,58,48));
        Save.setForeground(Color.white);
    }//GEN-LAST:event_board_19ActionPerformed

    private void selectedYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedYesActionPerformed
        TF_TimeLimit.setEnabled(true);
        timeLimit = Integer.parseInt(TF_TimeLimit.getText());
        Save.setBackground(new java.awt.Color(59,58,48));
        Save.setForeground(Color.white);
    }//GEN-LAST:event_selectedYesActionPerformed

    private void selectedNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedNoActionPerformed
        TF_TimeLimit.setEnabled(false);
        timeLimit=-1;
        Save.setBackground(new java.awt.Color(59,58,48));
        Save.setForeground(Color.white);
    }//GEN-LAST:event_selectedNoActionPerformed

    private void TF_TimeLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_TimeLimitActionPerformed
        int time=Integer.parseInt(TF_TimeLimit.getText());
        if(TF_TimeLimit.getText().trim().equals("") || time<=0){
            JOptionPane.showMessageDialog(null,"error time limit");
            TF_TimeLimit.setText("20");
            
        }
        Save.setBackground(new java.awt.Color(59,58,48));
        Save.setForeground(Color.white);
    }//GEN-LAST:event_TF_TimeLimitActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        Save.setBackground(new java.awt.Color(159,169,163));
        Save.setForeground(Color.black);
        widthBoardtemp=widthBoard;
        sizeBoardtemp=sizeBoard;    
        timeLimittemp=timeLimit;
        
    }//GEN-LAST:event_SaveActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        if (sizeBoard!=sizeBoardtemp || !timeLimit.equals(timeLimittemp)){
            widthBoard=widthBoardtemp;
            sizeBoard=sizeBoardtemp;    
            timeLimit=timeLimittemp;
            switch(sizeBoardtemp){
                case 19:{ board_19.setSelected(true); break;}
                case 15:{ board_15.setSelected(true); break;}
                case 10:{ board_10.setSelected(true); break;}
            }
            switch(timeLimittemp){
                case -1:{selectedNo.setSelected(true);  break;}
                default:{selectedYes.setSelected(true); TF_TimeLimit.setEnabled(true); break;}
            }
        }      
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void TF_TimeLimitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_TimeLimitKeyReleased
        int time=Integer.parseInt(TF_TimeLimit.getText());
        if(TF_TimeLimit.getText().trim().equals("") || time<=0){
            JOptionPane.showMessageDialog(null,"error time limit");
            TF_TimeLimit.setText("20");
        }
        timeLimit=Integer.parseInt(TF_TimeLimit.getText());
        Save.setBackground(new java.awt.Color(59,58,48));
        Save.setForeground(Color.white);
    }//GEN-LAST:event_TF_TimeLimitKeyReleased
    public int getWidthBoard(){
        return widthBoard;
    }
    public int getSizeBoard(){
        return sizeBoard;
    }
    public int getTimeLimit(){
        return timeLimit;
    }
    /**
     * @param args the command line arguments
     */
    private int widthBoard=28;
    private int sizeBoard=19;
    private Integer timeLimit=20;
    static int widthBoardtemp=28;
    static int sizeBoardtemp=19;
    static Integer timeLimittemp=20;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Save;
    private javax.swing.JTextField TF_TimeLimit;
    private javax.swing.JRadioButton board_10;
    private javax.swing.JRadioButton board_15;
    private javax.swing.JRadioButton board_19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup limitedTIme;
    private javax.swing.ButtonGroup mode;
    private javax.swing.JRadioButton selectedNo;
    private javax.swing.JRadioButton selectedYes;
    // End of variables declaration//GEN-END:variables
}